services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: sentinelx-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  influxdb:
    image: influxdb:2.7
    container_name: sentinelx-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD:-admin1234}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG:-sentinelx}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET:-telemetry}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN:-sentinelx-super-token-admin}
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.32
    container_name: sentinelx-telegraf
    restart: unless-stopped
    depends_on:
      - mosquitto
      - influxdb
    environment:
      INFLUX_ORG: ${INFLUX_ORG:-sentinelx}
      INFLUX_BUCKET: ${INFLUX_BUCKET:-telemetry}
      INFLUX_TOKEN: ${INFLUX_TOKEN:-sentinelx-super-token-admin}
      MQTT_TELEGRAF_PASSWORD: ${MQTT_TELEGRAF_PASSWORD:-telegraf-sx}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  api:
    build:
      context: ./FastAPI
    container_name: sentinelx-api
    restart: unless-stopped
    depends_on:
      - mosquitto
    ports:
      - "8000:8000"
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_USER: api
      MQTT_PASSWORD: ${MQTT_API_PASSWORD:-api-sx}
      HMAC_SECRET: ${HMAC_SECRET:-dev-secret-change-me}
      DB_PATH: /data/sentinel.db
    volumes:
      - api_data:/data

  grafana:
    image: grafana/grafana:11.2.0
    container_name: sentinelx-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-https://discord.com/api/webhooks/1556945500102467634/1weW7Ub1DpkdWjTQBQfvaV_D1cxmkY2409GbGIHqm7Sc0b6fZiytAJN5uCJvPa_VItAJ}
      INFLUX_ORG: ${INFLUX_ORG:-sentinelx}
      INFLUX_BUCKET: ${INFLUX_BUCKET:-telemetry}
      INFLUX_TOKEN: ${INFLUX_TOKEN:-sentinelx-super-token-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  mosquitto_data:
    external: true
    name: sentinelx-stack_mosquitto_data

  mosquitto_log:
    external: true
    name: sentinelx-stack_mosquitto_log

  influxdb_data:
    external: true
    name: sentinelx-stack_influxdb_data

  grafana_data:
    external: true
    name: sentinelx-stack_grafana_data

  api_data:
